name: Oglasi

on:
  schedule:
    # ┌───────────── minute (0 - 59)
    # │ ┌───────────── hour (0 - 23)
    # │ │ ┌───────────── day of the month (1 - 31)
    # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    # │ │ │ │ │
    # │ │ │ │ │
    # │ │ │ │ │
    # * * * * *
    - cron: '30 19 * * ?'

jobs:
  build:
    name: Fetch nepremicnine.net
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: yarn install
      # Fetch
      - run: yarn start:oglasi
        env:
          POSTGRESQL_URL: ${{ secrets.POSTGRESQL_URL }}
